### PR TITLE
Add a more tolerant vs runtime replacement

### PR DESCRIPTION
**Pull request by tonka3000**
This vs runtime replacement for the openssl mak files (required for Visual Studio/nmake) are more tolerant then the existing implementation (which leads to replacement errors in 1.0.2l).
The new function try to replace any existing vs runtime in the openssl mak files, if one is found, it will exit normally, but if no vs runtime is found in the file it will throw a Exception to guarentee that we have replaced the vs runtime.

Greetings
Tonka

### CODE REVIEW

**Comment by tonka3000** [comment]
The CI fails are confusing, appveyor fails with MinGW because of a missing parameter for gcc and travis build always throw error because of wrong username, password, but it is not the release branch.  
At the moment it is not possbile to install poco 1.7.9:stable (from conan center) from source, because OpenSSL 1.0.2l fails.  
Is the 1.0.2l branch to old and not supported anymore?

**Comment by lasote** [comment]
Hi @tonka3000 , yes, it looks like a problem with the package tools, let me take a look.

**Comment by lasote** [comment]
I see, it's about new security policy with travis:  https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

I have to think about how to solve this.

**Comment by lasote** [comment]
Solved, it was a bug in the latest conan package tools affecting the pull requests only. Let's see how it goes with your PR

**Comment by tonka3000** [comment]
Hey @lasote ,

please can you check the CI again, seems to work in most cases, but some error messages from CI are weird again.

I would need that fix in order to use this version with conan.

Thanks in advance

**Comment by lasote** [comment]
Yeah, it's weird, something is happening. By the way, as a user suggested here: https://github.com/lasote/conan-openssl/issues/33 it's easier to use the `strict=False` parameter to solve this problem, maybe we can try if it is related or not to the error. (I don't think so)

**Comment by lasote** [comment]
I've pushed the strict=False, should be ok now

**Comment by tonka3000** [comment]
The strict=False approach is buggy, i get a /MDdd flag (which will be ignored by the compiler) when i use compiler.runtime=MDd, so it fallback to the default settings, which could be bad!

**Pull request closed without merging**
