### PR TITLE
ARMv7 support

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

It's only possible to build OpenSSL on ARM when armv4 is defined on `./Configure`.  
This PR brings such definition when the target arch is armv7.

Regards.

### CODE REVIEW

**Comment by uilianries** [comment]
Any PR or new branch will fail because Travis replaces all env vars from settings by values in the file.

Maybe you could use Travis env vars instead to write on travis file, or use default values in build.py.  
Every new PR you need to review and check all build status manually when you could review and only expect all green.

**Comment by lasote** [comment]
Hi! It looks it's failing because of the https://github.com/lasote/conan-openssl/issues/33 issue. Could you introduce the `strict=False` and push again? The travis builds are working ok, what do  you mean with the env vars? 

Thanks, friend!

**Comment by lasote** [comment]
I've updated the release/1.0.2l with the strict=False, please update

**Comment by uilianries** [comment]
Yeah, I'll update ASAP. Thanks for communicate.

**Comment by uilianries** [comment]
@lasote Could you please re-run Travis? The errors were about timeout, as you saw on this week.

**Comment by lasote** [comment]
relaunched

**Pull request merged**
