### PR TITLE
- iOS and Simulator build support

### PR DESCRIPTION
**Pull request by SSE4**

### CODE REVIEW

**Comment by lasote** [comment]
Let's see how it goes with CI, travis is failing today a lot!

**Comment by SSE4** [comment]
yep, there are some errors of the following kind:
`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

**Comment by SSE4** [comment]
build finally passed

**Comment by Croydon** [comment]
@SSE4 This pull request has added makedepent as a dependency (on ubuntu it's included in the xutils-dev package), making the conan package even less self-contained

**Pull request merged**
