### PR TITLE
Added OpenSSL 1.1.0c

### PR DESCRIPTION
**Pull request by madduci**
Added compiling steps for OpenSSL 1.1.0 and disabled by default electric-fence and zlib, they must be enabled in the options explicitly (easier testing)

### CODE REVIEW

**Comment by lasote** [comment]
Thanks  @madduci . I will like to keep the zlib and efence options like the previous version, also the tested packages. I've created a new branch for 1.1.0c testing.

**Comment by madduci** [comment]
you're welcome, I have still to fix the prefix path in windows and adjust zlib.
I've opted-out it and efence just because it makes sense to enable them explicitly (e.g. efence in Debug mode?) instead of keeping them always on

**Comment by lasote** [comment]
@madduci maybe you are right, if some builds don't require efence we should not include it, but I'm not sure how to build openssl without efence, it fails. Maybe some flag? I've to investigate. Thanks!

**Comment by madduci** [comment]
yes, in addition I've noticed that there are problems on travis-ci and appveyor during the "make install" phase, but the build process looks fine

**Comment by Croydon** [comment]
Just wanted to add GCC5.4+6.2+6.3 to the testing/1.1.0c branch, however the branch looks really odd. All versions strings say 1.0.2i. Error?

**Comment by lasote** [comment]
I uploaded a branch for 1.1.0g. please try it!

**Pull request closed without merging**
